network:
  subnet: "192.168.178.0/24"  # Network to monitor
  scan_interval: 600          # Scan interval in seconds (10 minutes)
  port_scan_timeout: 0.5      # Timeout per port in seconds (reduced from 1s)
  max_concurrent_scans: 50    # Maximum number of concurrent scans (increased from 10)
